### ISSUE TITLE
Contribution to Hugging Face 🤗 cookbook: Add a Lang Chain agent that can interact with a PostgreSQL database

### ISSUE THREAD

**Issue by paartheee** [huggingface/cookbook#87] opened 2024-04-26 17:12 UTC
We can use the PostgreSQL database to feed additional context to LLMs. However, the naive approach to generating database queries is currently too brittle. Therefore, it is advisable to implement an agent and give it tools to interact with a graph database. The tools use predefined flows and allow agents to solve specific problems. we can use Mixtral 8x7b as an agent.

**Comment by aymeric-roucher** [comment] 2024-09-19 06:45
This is a nearly word-for-word duplicate of [this issue](https://github.com/huggingface/cookbook/issues/39):
>  You can use more than just vector databases to feed additional context to LLMs. However, the naive approach of generating database queries is too brittle at the moment. Therefore, it is advisable to implement an agent and give it tools to interact with a graph database. The tools use predefined flows and allow agent to solve specific problems. I have a version with OpenAI here: https://towardsdatascience.com/enhancing-interaction-between-language-models-and-graph-databases-via-a-semantic-layer-0a78ad3eba49 Would probably need to use Mixtral 8x7b as an agent.

Closing this, please don't generate other clones of existing issues!

**Closed by aymeric-roucher** 2024-09-19 06:45 UTC
